### PR TITLE
add includeOracleDeps parameter to Tree.remap()

### PR DESCRIPTION
**Pull request by bkeinert**

### CODE REVIEW

**Review by Yitzi2 — CHANGES_REQUESTED** [review]
While this will solve the issue you're facing, it is working around a more fundamental bug in how this function handles remaps of things other than X, Y, and Z which are not direct dependencies.
The proper fix, if I haven't fixed something, is in line 260, to replace depMap with m itself.  Then lines 253-259 (constructing depMap) can be removed, and no new parameter is needed (the current behavior can cause a remap of an operation to not be the corresponding operation on the remaps of the inputs, and is thus buggy).

Also, be aware that this will fix the case in which an oracle is transformed by one of the oracles you're replacing; the case in which the oracle you're replacing is itself transformed will not be handled by either this PR or the proposed fix-alternative.  To fix that, you'd need to go to transformed_oracle_clause.cpp, and have it check if deps_ contains underlying (and, if it does, use that replacement as newUnderlying).

**Review by 12parsecs — COMMENTED** [review]
this looks good and makes sense to me, but yitzi's comments imply that perhaps this should be discussed further

**Comment by smusuvathy** [comment]
@bkeinert should we close this PR?

**Comment by bkeinert** [comment]
Yes.

**Pull request closed without merging**
